import { ControlItem } from './types';

export const DEFAULT_ITEMS: ControlItem[] = [
  {
    id: 'manage-fobs',
    title: 'Manage fobs',
    icon: 'phone-portrait-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Manage\nfobs',
  },
  {
    id: 'delivery-pass',
    title: 'Create Delivery Pass',
    icon: 'key-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Create\nDelivery Pass',
  },
  {
    id: 'thermostat',
    title: 'Cool',
    subtitle: 'to 72°F',
    icon: 'snow-outline',
    iconColor: '#42A5F5',
    iconBg: '#FFFFFF',
    size: 'wide',
    section: 'quick-action',
    label: 'Thermostat control',
  },
  {
    id: 'front-door',
    title: 'Front door',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
  {
    id: 'side-door',
    title: 'Side door',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
];

export const AVAILABLE_ITEMS: ControlItem[] = [
  {
    id: 'my-unit',
    title: 'My unit',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
  {
    id: 'garage',
    title: 'Garage',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
  {
    id: 'bluetooth',
    title: 'Bluetooth',
    icon: 'bluetooth-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Bluetooth',
  },
  {
    id: 'package-room',
    title: 'Package room',
    icon: 'cube-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Package room',
  },
  {
    id: 'gym',
    title: 'Gym',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
  {
    id: 'pool',
    title: 'Pool',
    subtitle: 'Hold to unlock',
    icon: 'lock-closed',
    iconColor: '#AAAAAA',
    iconBg: '#EFEFEF',
    size: 'door',
    section: 'door',
  },
  {
    id: 'connect-payment',
    title: 'Connect payment',
    icon: 'card-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Connect\npayment',
  },
  {
    id: 'manage-video',
    title: 'Manage video',
    icon: 'videocam-outline',
    iconColor: '#6B4EFF',
    iconBg: '#EDE8FF',
    size: 'small',
    section: 'quick-action',
    label: 'Manage\nvideo',
  },
];

export const ALL_ITEMS: ControlItem[] = [...DEFAULT_ITEMS, ...AVAILABLE_ITEMS];
